stages:
    - set_up
    - run_tests
    - after_test_run

variables:
  PYTHON_IMAGE: python:3.10

run_pylint_quality_check:
    image: $PYTHON_IMAGE
    stage: set_up
    when: manual
    script:
      - ls
      - python -m pip install -r requirements.txt
      - pip install pylint
      - pylint -E ssqatest

build_set_up:
    image: $PYTHON_IMAGE
    stage: set_up
    script:
      - pwd
      - ls
      - python -m pip install -r requirements.txt
      - source variables_local.env
      - pip install --upgrade pip
    when: always

run_BE_Regression:
    image: $PYTHON_IMAGE
    stage: run_tests
    script:
      - pwd
      - ls
      - mkdir results
      - current_date=$(date '+%Y-%m-%d')
      - env
      - cd ssqatest
      - python -m pip install -r requirements.txt
      - pytest
#      - python3 -m pytest tests/backend -s
      - python3 -m pytest tests/backend --html=../results/${current_date}.html  --self-contained-html
      - echo "All Backend tests have run!"

    when : always

    artifacts:
      when: always
      paths:
        - results

test_tracebility:
  stage: after_test_run

  script:
    - echo "All tests in the regression suite have been run"
    - echo "Please check the artifacts folder"

  when: always

