stages:
    - code_quality
    - run_tests

variables:
  PYTHON_IMAGE: python:latest

#run_pylint_quality_check:
#    image: $PYTHON_IMAGE
#    stage: code_quality
#    script:
#      - ls
#      - python -m pip install -r requirements.txt
#      - pip install pylint
#      - pylint -E ssqatest

run_BE_Regression:
    image: $PYTHON_IMAGE
    stage: run_tests
    script:
      - pwd
      - ls
      - source variables_local.env
      - env
      - cd ssqatest
      - python3 -m pytest -m tests/backend
    when: always
