stages:
    - set_up
    - run_tests
    - deploy_prod

variables:
  PYTHON_IMAGE: python:3.10

run_pylint_quality_check:
    image: $PYTHON_IMAGE
    stage: set_up
    when: manual
    script:
      - ls
      - python -m pip install -r requirements.txt
      - pip install pylint
      - pylint -E ssqatest

build_set_up:
    image: $PYTHON_IMAGE
    stage: set_up
    script:
      - pwd
      - ls
      - pip install --upgrade pip


#      - python -m pip install -r requirements.txt
#      - source variables_local.env
#      - echo "Env variables are now set"
#      - env
#      - DELETE THESE 2 LINES LATER
#      - cd ssqatest
#      - python3 -m pytest tests/backend --html=../results/${current_date}.html  --self-contained-html
    when: always

run_BE_Regression:
    image: $PYTHON_IMAGE
    stage: run_tests
    script:
      - pwd
      - ls
      - source variables_local.env
      - env
      - mkdir results
      - dir
      - current_date=$(date '+%Y-%m-%d')
      - env
      - python -m pip install -r requirements.txt
#      - cd ssqatest

#      - python3 -m pytest tests/backend -s
#      - python3 -m pytest tests/backend --html=../results/${current_date}.html  --self-contained-html
      - /bin/sh ./runner.sh ssqatest/tests/backend
#      - /bin/sh ./runner.sh ssqatest/tests/backend
      - echo "The branch is:" ${CI_COMMIT_REF_NAME}
      - echo "This is from yml file - All Backend tests have run!"

    when : always

    artifacts:
      when: always
      paths:
        - results

test_tracebility:
  stage: deploy_prod

  script:
    - echo "All tests in the regression suite have been run"
    - echo "Please check the artifacts folder"

  when: always

