stages:
    - code_quality
    - run_tests

variables:
  PYTHON_IMAGE: python:3.10


#run_pylint_quality_check:
#    image: $PYTHON_IMAGE
#    stage: code_quality
#    script:
#      - ls
#      - python -m pip install -r requirements.txt
#      - pip install pylint
#      - pylint -E ssqatest

run_BE_Regression:
    image: $PYTHON_IMAGE
    stage: run_tests
    script:
      - pwd
      - ls
      - python -m pip install -r requirements.txt
      - source variables_local.env
      - env
      - cd ssqatest
      - python3 -m pytest -m be003 --html=./ssqatest/results/0982024_report.html  --self-contained-html
      - pwd
      - ls
    when: always

    artifacts:
      when: always
      paths:
        - ./ssqatest/results

