stages:
    -code_quality
    -run_tests
    
variables:
    
run_pylint_quality_check:
    script:
       -pylint demostore_frontend_backend_tests
       
run_BE_Regression: 
    scripts:
        -cd demostore_frontend_backend_tests
        -python3 -m pytest -m tests/backend
    